#version: '3'

services:
  erp:
    build: .
    ports:
      - "8003:8069"
    volumes:
      - ./modules:/mnt/extra-addons/
      - ./odoo_dev_conf:/etc/odoo
      - odoo-data:/var/lib/odoo
    depends_on:
      - db
      
    container_name: hospital_erp

    #command: odoo -u base
    #command: odoo scaffold Hospital_Management /mnt/extra-addons/

    networks:
      - erpnet

  db:
    image: postgres:17
    ports:
      - "5449:5432"
    env_file: .env
    container_name: hospital_postgres
    networks:
      - erpnet

networks:
  erpnet:
    driver: bridge

volumes:
  odoo-data:
